import { HipHopTerm, FlowType, SongDnaSection } from '../types';

export const HIP_HOP_TERMS: HipHopTerm[] = [
  {
    id: 'bar',
    term: 'Bar (Measure)',
    category: 'Structure',
    definition: 'A single metric unit of time containing 4 beats in a standard 4/4 hip-hop time signature; colloquially refers to a single line or punchline of rap lyrics.',
    simpleExplanation: 'When a rapper writes a 16-bar verse, they are writing 16 rhythmic musical measures.',
    desiRapExample: 'KR$NA in No Cap: "Har bar mein barood, har line mein proof."',
    hindiExample: 'हर बार में बारूद, हर लाइन में प्रूफ',
    relatedTerms: ['Verse', 'BPM', 'Hook', 'Cadence']
  },
  {
    id: 'verse',
    term: 'Verse',
    category: 'Structure',
    definition: 'The main lyrical storytelling block of a rap song, typically consisting of 16 bars (or 12-24 bars) positioned between recurring choruses.',
    simpleExplanation: 'The verses are where the MC tells their story, unloads metaphors, and drives the song forward.',
    desiRapExample: 'Encore ABJ in Seedhe Maut\'s "Maina" delivering a 24-bar introspective verse on childhood ambition.',
    hindiExample: 'छत पे बैठा पंछी देखूँ, उड़ने का हौसला ढूँढूँ',
    relatedTerms: ['Bar', 'Hook', 'Bridge', 'Song DNA']
  },
  {
    id: 'hook',
    term: 'Hook (Chorus)',
    category: 'Structure',
    definition: 'The most memorable, repetitive, and melodically catchy section of a rap song designed to stick in the listener\'s mind.',
    simpleExplanation: 'The part of the song that the whole stadium sings along to.',
    desiRapExample: 'DIVINE’s "Mere gully mein, mere gully mein... 24 ghante chaukanna."',
    hindiExample: 'मेरे गली में, मेरे गली में... 24 घंटे चौकन्ना',
    relatedTerms: ['Verse', 'Intro', 'Outro']
  },
  {
    id: 'flow',
    term: 'Flow',
    category: 'Rhyme & Flow',
    definition: 'The distinct rhythm, cadence, velocity, and rhyme placement that a rapper uses to deliver their words over an instrumental beat.',
    simpleExplanation: 'How the words ride the drums—whether fast, bouncy, laid-back, or staccato.',
    desiRapExample: 'Calm (Seedhe Maut) switching from half-time into a triplet flow on "Nanchaku".',
    hindiExample: 'नानचाकू घुमाते जैसे ब्रूस ली',
    relatedTerms: ['Cadence', 'Delivery', 'Pocket', 'BPM']
  },
  {
    id: 'cadence',
    term: 'Cadence',
    category: 'Rhyme & Flow',
    definition: 'The melodic inflection, rhythmic pitch modulation, and accentuation pattern an MC gives to syllables within a bar.',
    simpleExplanation: 'The musical rise and fall in a rapper\'s voice that makes the words bounce.',
    desiRapExample: 'Raftaar’s rhythmic vocal pitch changes in "Sheikh Chilli".',
    hindiExample: 'आवाज का उतार-चढ़ाव जो बीट पे उछाल लाए',
    relatedTerms: ['Flow', 'Delivery', 'Bar']
  },
  {
    id: 'delivery',
    term: 'Delivery',
    category: 'Rhyme & Flow',
    definition: 'The emotional conviction, vocal texture, breath control, and theatrical energy projected when reciting rap lyrics.',
    simpleExplanation: 'It is not just what you say, but the raw attitude and power with which you say it.',
    desiRapExample: 'Gravity’s commanding, booming baritone vocal projection on "Jalwa".',
    hindiExample: 'गहरी और भारी आवाज़ का दम',
    relatedTerms: ['Flow', 'Cadence', 'Voice Modulation']
  },
  {
    id: 'multisyllabic-rhyme',
    term: 'Multisyllabic Rhyme (Multis)',
    category: 'Rhyme & Flow',
    definition: 'A rhyme scheme where multiple corresponding syllables in two or more words/lines rhyme with each other.',
    simpleExplanation: 'Instead of just rhyming one syllable, you rhyme whole multi-word patterns together.',
    desiRapExample: 'KR$NA rhyming 4-syllable compound Urdu/Hindi words across 8 continuous bars.',
    hindiExample: 'जादूगर / बाजू पर / काबू कर',
    relatedTerms: ['Internal Rhyme', 'Scheme', 'Bar']
  },
  {
    id: 'cypher',
    term: 'Cypher',
    category: 'Culture & Street',
    definition: 'A circular gathering of MCs, beatboxers, B-boys, and DJs who take turns freestyling, dropping 16s, and collaborating in real-time.',
    simpleExplanation: 'The sacred circle where hip-hop culture is shared on the streets without competition ego.',
    desiRapExample: 'The historic Gully Gang Cypher at Bandra Fort amphitheater.',
    hindiExample: 'गली के कोने पे दोस्तों का घेरा और माइक पे आग',
    relatedTerms: ['Freestyle', 'MC', 'Breaking', 'Battle']
  },
  {
    id: '808',
    term: '808 (Sub-Bass)',
    category: 'Production',
    definition: 'A low-frequency, deep electronic sub-bass drum originally generated by the Roland TR-808 drum machine.',
    simpleExplanation: 'The deep, rumbling bass you feel in your chest in trap and drill songs.',
    desiRapExample: 'The sliding 808s engineered by Sez on the Beat in Seedhe Maut’s "Nanchaku".',
    hindiExample: 'छाती चीरने वाला गहरा बास',
    relatedTerms: ['BPM', 'Kick', 'Snare', 'Beat']
  }
];

export const FLOW_TYPES: FlowType[] = [
  {
    id: 'straight-flow',
    name: 'Straight 16th Flow',
    bpm: 90,
    bpmRecommended: 90,
    timeDivision: '1/16 Standard Grid',
    description: 'Evenly spaced 4 syllables per beat, landing squarely on the 1, 2, 3, 4 grid. The classic golden-era boom-bap rhythm.',
    patternVisual: ['TA', 'ka', 'ta', 'ka', '|', 'TA', 'ka', 'ta', 'ka', '|', 'TA', 'ka', 'ta', 'ka', '|', 'TA', 'ka', 'ta', 'ka'],
    famousExample: {
      artist: 'DIVINE',
      song: 'Kohinoor',
      bar: 'JB Nagar se sidha New York, ab chhota bacha nahi karta talk'
    },
    audioBeepPattern: [1, 1, 1, 1]
  },
  {
    id: 'triplet-flow',
    name: 'Triplet Flow (Migos Flow)',
    bpm: 135,
    bpmRecommended: 135,
    timeDivision: '1/8 Triplets',
    description: 'Dividing each beat into 3 equal syllables (1-e-and, 2-e-and). Creates a bouncy, relentless forward propulsion popular in trap.',
    patternVisual: ['ONE', 'two', 'three', '|', 'FOUR', 'five', 'six', '|', 'SEV', 'eight', 'nine', '|', 'TEN', 'el', 'eve'],
    famousExample: {
      artist: 'Seedhe Maut (Calm)',
      song: 'Nanchaku',
      bar: 'Nanchaku ghumaate jaise Bruce Lee, mic pe baithe to saare freeze'
    },
    audioBeepPattern: [1.33, 1.33, 1.33]
  },
  {
    id: 'double-time',
    name: 'Double Time (Chopper Flow)',
    bpm: 88,
    bpmRecommended: 88,
    timeDivision: '1/32 High Velocity',
    description: 'Doubling the syllable density to 8 syllables per beat. Requires extreme breath control, enunciation, and tongue agility.',
    patternVisual: ['1-2-3-4-5-6-7-8', '1-2-3-4-5-6-7-8', '1-2-3-4-5-6-7-8', '1-2-3-4-5-6-7-8'],
    famousExample: {
      artist: 'Raftaar',
      song: 'Aisi Taisi',
      bar: 'Speed meri rocket jaise space mein, koi na bacha iss race mein'
    },
    audioBeepPattern: [0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5]
  },
  {
    id: 'syncopated-flow',
    name: 'Syncopated / Off-Grid Flow',
    bpm: 92,
    bpmRecommended: 92,
    timeDivision: 'Syncopated Rest & Off-Beat',
    description: 'Intentionally stressing the off-beats and leaving strategic silence where the ear expects a rhyme.',
    patternVisual: ['..', 'and', 'TWO', '..', '|', 'and', 'THREE', '..', 'and', 'FOUR'],
    famousExample: {
      artist: 'Yashraj',
      song: 'Dhundhla',
      bar: 'Raatein dhundhli... yaadein saaf... sheher so gaya hum jaagte'
    },
    audioBeepPattern: [0, 1, 0, 1]
  }
];

export const FLOW_LAB_TYPES = FLOW_TYPES;

export const SONG_STRUCTURE_PARTS: SongDnaSection[] = [
  {
    name: 'INTRO',
    bars: '4 – 8 Bars',
    typicalLength: '4 – 8 Bars',
    purpose: 'Sets atmospheric mood, introduces the beat loop, and builds anticipation.',
    energyLevel: 35,
    writingStyle: 'Spoken ad-libs, signature producer tags ("Sez on the beat boy").',
    productionLayer: 'Filtered synth pad, muted drums, vinyl crackle.',
    proTip: 'Use a catchy 1-line vocal signature before the beat drops.'
  },
  {
    name: 'VERSE 1',
    bars: '16 Bars',
    typicalLength: '16 Bars',
    purpose: 'Establishes the narrative premise and introduces the rhyme scheme.',
    energyLevel: 75,
    writingStyle: 'Complex storytelling, multis, internal rhymes.',
    productionLayer: 'Full kick & snare drum groove, baseline 808 sub.',
    proTip: 'Frontload a memorable opening punchline to hook listeners in the first 4 bars.'
  },
  {
    name: 'HOOK (CHORUS)',
    bars: '8 Bars',
    typicalLength: '8 Bars',
    purpose: 'The central thematic takeaway and catchiest melodic climax.',
    energyLevel: 95,
    writingStyle: 'Repetitive anthemic phrases, high melody for crowd singalongs.',
    productionLayer: 'Layered stereo vocals, double-tracked adlibs, maximum loudness.',
    proTip: 'Keep lyrics simple and rhythmic so a live crowd can scream it back instantly.'
  },
  {
    name: 'VERSE 2',
    bars: '16 Bars',
    typicalLength: '16 Bars',
    purpose: 'Escalates the story, switches cadence to surprise the listener.',
    energyLevel: 85,
    writingStyle: 'Double-time flow switches, punchline combos.',
    productionLayer: 'Hi-hat rolls, syncopated percussion variations.',
    proTip: 'Switch flow pocket mid-verse (e.g. from straight 16ths to triplets).'
  },
  {
    name: 'BRIDGE / BEAT SWITCH',
    bars: '4 – 8 Bars',
    typicalLength: '4 – 8 Bars',
    purpose: 'Provides sonic contrast and emotional breathing room.',
    energyLevel: 60,
    writingStyle: 'Melodic singing, pitch changes, altered perspective.',
    productionLayer: 'Half-time drum pattern, modulated bass, filtered vocals.',
    proTip: 'Strip back the heavy drums and let the vocal melody carry the weight.'
  },
  {
    name: 'OUTRO',
    bars: '4 – 8 Bars',
    typicalLength: '4 – 8 Bars',
    purpose: 'Resolves sonic energy and fades into silence.',
    energyLevel: 30,
    writingStyle: 'Fade-out ad-libs, philosophical closing remarks.',
    productionLayer: 'Decaying reverb trails, lone piano or synth chord.',
    proTip: 'Let the instrumental breathe for a few bars after the final vocals end.'
  }
];

export const SONG_DNA_SECTIONS = SONG_STRUCTURE_PARTS;

export const HIP_HOP_ELEMENTS = [
  {
    name: 'MCing / Rapping',
    icon: '🎤',
    description: 'The vocal craft of rhyme, rhythm, storytelling, and wordplay over beats.',
    indianContext: 'Adapted into multiple Indian languages (Hindi, Marathi, Punjabi, Tamil, Malayalam, Bengali, Kannada) with rich local metaphors.',
    keyFigures: ['DIVINE', 'Seedhe Maut', 'KR$NA', 'Bohemia', 'MC Stan', 'Arivu']
  },
  {
    name: 'DJing / Beat Production',
    icon: '🎧',
    description: 'The sonic foundation: vinyl turntablism, beat juggling, sampling, and 808 synthesis.',
    indianContext: 'Pioneered by producers fusing traditional Indian classical samples (flute, sitar, tabla, shehnai) with modern 808 trap and drill.',
    keyFigures: ['Sez on the Beat', 'Karan Kanchan', 'Phenom', 'Kalmi', 'Sikander Kahlon']
  },
  {
    name: 'Breaking / B-Boying',
    icon: '👟',
    description: 'The athletic, acrobatic dance movement born in the South Bronx and practiced on cardboard and street parks.',
    indianContext: 'Brought Indian b-boys to Red Bull BC One World Finals; powerhouse crews in Mumbai, Delhi, and Bengaluru.',
    keyFigures: ['Flying Machine (Arif Chaudhary)', 'Wild Ripperz', 'Underdogz', 'Roc Fresh Crew']
  },
  {
    name: 'Graffiti / Street Art',
    icon: '🎨',
    description: 'Visual typography, character murals, and aerosol art claiming public spaces and walls.',
    indianContext: 'Transformed Mumbai chawls, Delhi flyovers, and Bandra walls into living street art galleries.',
    keyFigures: ['Zake', 'Daks', 'Bond', 'Mooz', 'Yantr']
  }
];

export const WOMEN_IN_DHH = [
  {
    name: 'Dee MC',
    city: 'Mumbai',
    role: 'Rapper & Activist',
    impact: 'Pioneered female representation in Mumbai rap; judge on MTV Hustle and international showcase performer.',
    notableTracks: ['No Make Up', 'Rang', 'Talk To Me']
  },
  {
    name: 'Srushti Tawade',
    city: 'Mumbai',
    role: 'Storytelling MC',
    impact: 'Broke viral internet records with her witty, theatrical satire "Chill Kinda Guy" and "Main Nahi Toh Kaun".',
    notableTracks: ['Main Nahi Toh Kaun', 'Chill Kinda Guy', 'Ek Tha Kauwa']
  },
  {
    name: 'Siri (Siri Narayan)',
    city: 'Bengaluru',
    role: 'Multilingual Rapper',
    impact: 'Smooth multilingual flow switching across Kannada, Telugu, Hindi, and English with futuristic cyberpunk visuals.',
    notableTracks: ['My Jam', 'Ta Ra Ra', 'Gimme Some More']
  },
  {
    name: 'Ira',
    city: 'Delhi',
    role: 'Underground MC',
    impact: 'Fierce, technical boom-bap delivery and raw street consciousness addressing women\'s safety and independence.',
    notableTracks: ['Delhi Girl', 'Khatam', 'Azaadi']
  }
];

export const FASHION_STYLES = [
  {
    style: 'Gully Oversized Streetwear',
    description: 'Drop-shoulder heavy cotton tees, baggy cargo pants, bucket hats, and retro sneakers.',
    keyItems: ['Oversized Tees', 'Cargo Pants', 'Nike Air Force 1s', 'Bandanas', 'Chains'],
    associatedArtists: ['DIVINE', 'MC Stan', 'Seedhe Maut']
  },
  {
    style: 'Delhi Winter Layering & Techwear',
    description: 'Puffer jackets, tactical vests, balaclavas, utility chest rigs, and monochromatic tracksuits.',
    keyItems: ['Puffers', 'Tactical Vests', 'Balaclavas', 'Jordans', 'Tech Cargoes'],
    associatedArtists: ['KR$NA', 'Prabh Deep', 'Rebel 7']
  },
  {
    style: 'Bling, Grillz & High Fashion Fusion',
    description: 'Diamond cuban link chains, custom iced-out pendants, customized denim, and luxury sneakers.',
    keyItems: ['Cuban Chains', 'Custom Grillz', 'Designer Sunglasses', 'Graphic Denim'],
    associatedArtists: ['MC Stan', 'King', 'Karan Aujla']
  }
];

